### ISSUE TITLE
Passing non array var to reset function

### ISSUE THREAD

**Issue by reyder** [Prophet731/BFAdminCP#108]
[2015-10-03 18:53:32] production.ERROR: exception 'ErrorException' with message 'Invalid operand type was used: expecting an array' in /home/dzieju/www/dzieju.pl/vendor/laravel/framework/src/Illuminate/Support/helpers.php:556
Stack trace:
#0 /home/dzieju/www/dzieju.pl/vendor/laravel/framework/src/Illuminate/Support/helpers.php(556): Illuminate\Exception\Handler->handleError()
#1 /home/dzieju/www/dzieju.pl/app/bfacp/Helpers/Battlefield.php(362): head()

**Comment by Prophet731** [comment]
What were you trying to do? What page did that occur on?

**Comment by mikedevita** [comment]
I think i am getting a similar error but on the livescoreboard, checkout issue #109
