### ISSUE TITLE
Live Scoreboard Isn't working, throwing fatal error

### ISSUE THREAD

**Issue by mikedevita** [Prophet731/BFAdminCP#109]
> Fatal Error! The request couldn't complete due to a server side error. Please choose another server or retry. Notify an administrator if this error persists.

I can see chat logs, players and associated stats of players.. it is just the livescoreboard which is freaking out.

 looks like logs are throwing an error.. When i go to http://admincp.otcclan.com/api/servers/scoreboard/4

> reset() expects parameter 1 to be array, string given

looks like `app/storage/logs/` has the following...

```
  1 [2015-10-10 20:46:41] production.ERROR: exception 'ErrorException' with message 'reset() expects parameter 1 to be array, string given' in /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php:556
  2 Stack trace:
  3 #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'reset() expects...', '/var/www/adminc...', 556, Array)
  4 #1 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php(556): reset('MapNameNotFound...')
  5 #2 /var/www/admincp.otcclan.com/app/bfacp/Repositories/Scoreboard/LiveServerRepository.php(680): head('MapNameNotFound...')
  6 #3 /var/www/admincp.otcclan.com/app/bfacp/Repositories/Scoreboard/LiveServerRepository.php(702): BFACP\Repositories\Scoreboard\LiveServerRepository->getMapList()
  7 #4 /var/www/admincp.otcclan.com/app/bfacp/Repositories/Scoreboard/LiveServerRepository.php(973): BFACP\Repositories\Scoreboard\LiveServerRepository->getNextMap()
  8 #5 /var/www/admincp.otcclan.com/app/bfacp/Repositories/Scoreboard/LiveServerRepository.php(223): BFACP\Repositories\Scoreboard\LiveServerRepository->serverinfo()
  9 #6 /var/www/admincp.otcclan.com/app/bfacp/Http/Controllers/Api/ServersController.php(99): BFACP\Repositories\Scoreboard\LiveServerRepository->attempt()
 10 #7 [internal function]: BFACP\Http\Controllers\Api\ServersController->scoreboard('4')
 11 #8 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
 12 #9 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('scoreboard', Array)
 13 #10 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(BFACP\Http\Controllers\Api\ServersController), Object(Dingo\Api\Routing\    Route), 'scoreboard')
 14 #11 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Dingo\Api\Routing\Route), Object(Illuminate\Http\Request), 'BFACP\Http\Cont...',     'scoreboard')
 15 #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('4')
 16 #13 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
 17 #14 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
 18 #15 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
 19 #16 /var/www/admincp.otcclan.com/vendor/dingo/api/src/Routing/Router.php(216): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
 20 #17 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
 21 #18 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
 22 #19 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
 23 #20 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
 24 #21 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
 25 #22 /var/www/admincp.otcclan.com/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
 26 #23 /var/www/admincp.otcclan.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
 27 #24 /var/www/admincp.otcclan.com/public/index.php(49): Illuminate\Foundation\Application->run()
 28 #25 {main} [] []

```

**Comment by Prophet731** [comment]
You need to be running PHP 5.5 or higher, otherwise it will throw this error.

**Comment by mikedevita** [comment]
```

PHP 5.5.9-1ubuntu4.13 (cli) (built: Sep 29 2015 15:24:49)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

```

**Comment by Prophet731** [comment]
Ok one sec

**Comment by Prophet731** [comment]
http://www.adkgamers.com/topic/117610-bfacp-version-200/page-9#entry434102

Looks like you're missing a map I think. Are you running the new maps for battlefield 4?

**Comment by mikedevita** [comment]
yes we are, let me see if this resolves the issue.

**Comment by mikedevita** [comment]
yes that fixed my problem, thank you for the very very quick response.. awesome work on this btw.
